kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-conf
  namespace: thanos
data:
  config.yaml: |-
    # global:
    #   resolve_timeout: 5m
    # route:
    #   group_by: ['alertname', 'cluster', 'service']
    #   group_wait: 30s
    #   group_interval: 5s
    #   repeat_interval: 10s  
    #   receiver: 'web.hook'
    # receivers:
    # - name: 'web.hook'
    #   webhook_configs:
    #   - url: 'http://127.0.0.1:5000'
    "global":
      "resolve_timeout": "5m"
      smtp_smarthost: 'smtp.163.com:465' # 邮箱smtp服务器代理
      smtp_from: '15622245721@163.com' # 发送邮箱名称
      smtp_auth_username: '15622245721@163.com' # 邮箱名称
      smtp_auth_password: 'AZKSCGZBVMHXVXHG' # 授权密码
      smtp_require_tls: false # 不开启tls 默认开启
    "inhibit_rules":
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "critical"
      "target_match_re":
        "severity": "warning|info"
    - "equal":
      - "namespace"
      - "alertname"
      "source_match":
        "severity": "warning"
      "target_match_re":
        "severity": "info"
    "receivers":
    - "name": "Default"
      email_configs: # 邮箱配置
      - to: "zxw270194330@163.com" # 接收警报的email配置
    - "name": "Watchdog"
    - "name": "Critical"
    "route":
      "group_by":
      - "namespace"
      "group_interval": "5m"
      "group_wait": "30s"
      "receiver": "Default"
      "repeat_interval": "12h"
      "routes":
      - "match":
          "alertname": "Watchdog"
        "receiver": "Watchdog"
      - "match":
          "severity": "critical"
        "receiver": "Critical"