apiVersion: v1
kind: Secret
metadata:
  name: thanos-objectstorage
  namespace: thanos
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.thanos.svc.cluster.local:9000
      access_key: zhaoxw
      secret_key: qwe123qwe?
      insecure: true
      signature_version2: false
